# _________________________________
#
# ---- TRANSFORM SEQUENTIAL EXAMPLE ----
# _________________________________
#

method: "sequential"
name: "Sequential example"

mandatory_transforms_start:
#    #  - resize :
#    #      shape : [512, 512, 3]
#    #      keep_aspect : True
#    #      padding : 0
      - name: "normalize_image"
        # module : "" optional
        kwargs:
          mean: [128.0, 128.0, 128.0]
          standard_deviation: 255

transforms:
    - # module: "" #optional
      name: "blur"
      kwargs:
        kernel_size : 3
    - # module :"" # optional
      name : "random_blur"
      kwargs:
        kernel_size_min: 15
        kernel_size_max : 21
    - # module : "" # optional
      name : "example_function"
      kwargs :
        parameters : 1

mandatory_transforms_end: Null