#___________________________________
#
# ---- TRANSFORM SOMEOF EXAMPLE ----
# __________________________________
#

method: "someof"
name: "SomeOf example"
num_transformations : 3             #If used, comment "num_transformations_min" and  "num_transformations_max"
#num_transformations_min : 1        #If used, comment "num_transformations"
#num_transformations_max : 5        #If used, comment "num_transformations"


mandatory_transforms_start:
#    #  - resize :
#    #      shape : [512, 512, 3]
#    #      keep_aspect : True
#    #      padding : 0
      - name: "normalize_image"
        kwargs:
          mean: [128, 128, 128]
          standard_deviation: 255

transforms:
    - # module: "" #optional
      name: "blur"
      kwargs:
        kernel_size : 3
    - # module :"" # optional
      name : "random_blur"
      kwargs:
        kernel_size_min: 15
        kernel_size_max : 21
    - # module : "" # optional
      name : "example_function"
      kwargs :
        parameters : 1

mandatory_transforms_end: Null
