# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Optionally set the version of Python and requirements required to build your docs
#python:
#   version: 3.7
#   install:
#      - requirements: docs/requirements.txt
#      - method: setuptools
#        path: package
#   system_packages: true

mkdocs:
  configuration: docs/mkdocs.yml

# Build ePub (pdf is currently failing)
formats: all

build:
  image: latest

## pip requirements file for building sphinx docs (e.g. nbsphinx)
#requirements_file: docs/requirements.txt


# Use python 3 for building
python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt