site_name: Deeplodocus Documentation
site_description: 'Documentation of Deeplodocus, Flexible and Modular Deep Learning Framework.'
site_url: http://deeplodocus.org
# google_analytics: ['UA-36723568-3', 'mkdocs.org']

repo_url: http://github.com/Deeplodocus/deeplodocus
edit_uri: http://github.com/Deeplodocus/deeplodocus

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - python

# theme: readthedocs
docs_dir: 'docs'

nav:
    - Home: index.md
    - Installation : installation.md
    - Getting Started: getting_started.md
    - Examples: examples.md
    - Admin Commands : admin_commands.md
    - Brain : brain.md
    - Configuration: config.md
    - Data: data.md
    - Models: models.md
    - Transforms : transforms.md
    - Tips and Tricks: tips&tricks.md
    - About: about.md
