dataloader:
  batch_size: 4
  num_workers: 4
dataset:
  train:
    number: 100
    inputs:
      - ['./data/input1.txt']
      - ['./data/input2.txt']
    labels:
      - ["./data/label1.txt"]
    additional_data:
      - Null
  validation:
    number : 100
    inputs:
      - ['./data/input1.txt']
      - ['./data/input2.txt']
    labels:
      - ["./data/label1.txt"]
    additional_data:
      - Null
  test:
    number: 100
    inputs:
      - ['./data/input1.txt']
      - ['./data/input2.txt']
    labels:
      - ["./data/label1.txt"]
    additional_data:
      - Null
