dataloader:
  batch_size: 4
  num_workers: 4
dataset:
  train:
    inputs:
      - ['input1-1.txt', 'input1-2.txt']
      - "input2.txt"
    labels:
      - "labels1.txt"
      - "labels2.txt"
    additional_data:
      - "additional.txt"
  validation:
    inputs:
      - ['input1-1.txt', 'input1-2.txt']
      - "input2.txt"
    labels:
      - "labels1.txt"
      - "labels2.txt"
    additional_data:
      - "additional.txt"
  test:
    inputs:
      - ['input1-1.txt', 'input1-2.txt']
      - "input2.txt"
    labels:
      - "labels1.txt"
      - "labels2.txt"
    additional_data:
      - "additional.txt"
