dataloader:
  batch_size: 4
  num_workers: 4
dataset:
  train:
    inputs:
      - ['./data/input1.txt', './data/input1.txt']
      - ['./data/input2.txt', './data/input2.txt']
    labels:
      - ["./data/label1.txt", "./data/label2.txt"]
    additional_data:
      - "./data/additional_data.txt"
  validation:
    inputs:
      - ['./data/input1.txt', './data/input1.txt']
      - ['./data/input2.txt', './data/input2.txt']
    labels:
      - ["./data/label1.txt", "./data/label2.txt"]
    additional_data:
      - "./data/additional_data.txt"
  test:
    inputs:
      - ['./data/input1.txt', './data/input1.txt']
      - ['./data/input2.txt', './data/input2.txt']
    labels:
      - ["./data/label1.txt", "./data/label2.txt"]
    additional_data:
      - "./data/additional_data.txt"
