dataloader:
  batch_size: 4
  num_workers: 4
dataset:
  train:
    number: 100
    load_method: "default" #default (from memory), hard drive, ...
    inputs:
      - path: ['./data/input1.txt']
        join: Null # Null, auto, "some/path"      # (Optional) Null, auto, "some/path"
        type: "image"                             # (Optional) image, video, integer, label,
      - path: ['./data/input2.txt']
        join: Null                                # (Optional) Null, auto, "some/path"
        type: "image"                             # (Optional) image, video, integer, label,
    labels:
      - path: ['./data/label1.txt']
        type: "integer"
    additional_data:
      - Null
  validation:
    number : 7
    load_method: "default" #default (from memory), hard drive, ...
    inputs:
      - path: ['./data/input1.txt']
        join: Null # Null, auto, "some/path"      # (Optional) Null, auto, "some/path"
        type: "image"                             # (Optional) image, video, integer, label,
      - path: ['./data/input2.txt']
        join: Null                                # (Optional) Null, auto, "some/path"
        type: "image"                             # (Optional) image, video, integer, label,
    labels:
      - path: ['./data/label1.txt']
        type: "integer"
    additional_data:
      - Null
  test:
    number: 7
    load_method: "default" #default (from memory), hard drive, ...
    inputs:
      - path: ['./data/input1.txt']
        join: Null # Null, auto, "some/path"      # (Optional) Null, auto, "some/path"
        type: "image"                             # (Optional) image, video, integer, label,
      - path: ['./data/input2.txt']
        join: Null                                # (Optional) Null, auto, "some/path"
        type: "image"                             # (Optional) image, video, integer, label,
    labels:
      - path: ['./data/label1.txt']
        type: "integer"
    additional_data:
      - Null
