# ______________
#
# ---- MAIN ----
# ______________
#
# This is the main config file. Its path has to be given to the deeplodocus brain as input.
# This config file gives the path to other config files
# The required config files are :
#     - project
#     - data
#     - transform
#     - network
#     - optimizer
#     - metrics
#     - loss
#     - history
#     - ...


project: "project.yaml"
data: "data.yaml"
transform : "transform.yaml"
# network : "network.yaml"
optimizer: "optimizer.yaml"
# metrics: "metrics.yaml"
# loss: "loss.yaml"
# history : "history.yaml"



