train:                                                                              # Training entries
    name: "Train Transform Manager"
    inputs :
      - "/home/alix/Documents/deeplodocus/deeplodocus/core/project/deep_structure/config/transforms/transform_input1.yaml"
      - "transforms/transform_input2.yaml"
    labels :
      - None
      - None
    additional_data:
      - None
validation:                                                                        # Validation entries
    name: "Validation Transform Manager"
    inputs:
      - ["input1-1.txt", "input1-2.txt"]
      - "input2.txt"
    labels:
      - "labels1.txt"
      - "labels2.txt"
    additional_data:
      - "additional.txt"
test:                                                                               # Test entries
    name: "Validation Transform Manager"

    inputs:
      - ["input1-1.txt", "input1-2.txt"]
      - "input2.txt"
    labels:
      - "labels1.txt"
      - "labels2.txt"
    additional_data:
      - "additional.txt"