train:
  name: "Train Transform Manager"
  inputs:
   - "/home/alix/Documents/deeplodocus/deeplodocus/core/project/deep_structure/config/transforms/transform_input1.yaml"
   - "*input:0"
  labels:
   - Null
   - Null
  additional_data:
   - Null
validation:
  name: "Validation Transform Manager"
  inputs:
   - "/home/alix/Documents/deeplodocus/deeplodocus/core/project/deep_structure/config/transforms/transform_input1.yaml"
   - "*input:0"
  labels:
   - Null
   - Null
  additional_data:
   - Null
test:
  name: "Validation Transform Manager"
  inputs:
   - Null
   - Null
  labels:
   - Null
   - Null
  additional_data:
   - Null
