#___________________________________
#
# ---- TRANSFORM SOMEOF EXAMPLE ----
# __________________________________
#

method: "sequential"
name: "Label Transform"

mandatory_transforms_start: Null

transforms: Null

mandatory_transforms_end: Null
