dataloader:
  batch_size: 16
  num_workers: 4
enabled:
  train: True
  validation: True
  test: True
dataset:
  train:
    name: Null
    number: 10000
    inputs:
      - source: ['../../data/input1.txt']
        join: ["../../data/"] # Null, auto, "some/path"      # (Optional) Null, auto, "some/path"
        type: "image"                             # (Optional) image, video, integer, label,
        load_method: "default" #default (online), offline, online
    labels:
      - source: ['../../data/label1.txt']
        join: Null
        type: "integer"
        load_method: "default" #default (online), offline, online
    additional_data:
      - Null
  validation:
    name: Null
    number : 7
    inputs:
      - source: ['../../data/input1.txt']
        join: ["../../data/"] # Null, auto, "some/path"      # (Optional) Null, auto, "some/path"
        type: "image"                             # (Optional) image, video, integer, label,
        load_method: "default" #default (online), offline, online
    labels:
      - source: ['../../data/label1.txt']
        join: Null
        type: "integer"
        load_method: "default" #default (online), offline, online
    additional_data:
      - Null
  test:
    name: Null
    number : 7
    inputs:
      - source: ['../../data/input1.txt']
        join: Null # Null, auto, "some/path"      # (Optional) Null, auto, "some/path"
        type: "image"                             # (Optional) image, video, integer, label,
        load_method: "default" #default (online), offline, online
      - source: ['../../data/input2.txt']
        join: Null                                # (Optional) Null, auto, "some/path"
        type: "image"                             # (Optional) image, video, integer, label,
        load_method: "default" #default (online), offline, online
    labels:
      - source: ['../../data/label1.txt']
        type: "integer"
        load_method: "default" #default (online), offline, online
    additional_data:
      - Null
